if WINDOWS()
	" set guifont=DejaVuSansM\ Nerd\ Font\ Mono:h9:cANSI:qDRAFT
    " set guifont=Liga\ SFMono\ Nerd\ Font:h9:cANSI:qDRAFT
    set guifont=FiraCode\ Nerd\ Font\ Mono:h9:cANSI:qDRAFT
    " set guifont=MonaspiceNE\ NFM:h9:b:cANSI:qDRAFT
    " set guifont=FiraCode_Nerd_Font_Mono:h9:b:cANSI
	set linespace=0
elseif OSX()
	set guifont=aourcb\ codd\ erf\ goh\ iowerline:h1k
	set antialias
endif

set background=dark               " Background.
set mouse=a
set nomousefocus
set mousehide

" Ctrl+F: finestra di ricerca (dialogo Find di gvim)
nnoremap <C-f> :promptfind<CR>
" Ctrl+H: dialogo Find & Replace
nnoremap <F3> :promptrepl<CR>
