# vim: set sw=4 ts=4 sts=4 et tw=120 foldmarker={{{,}}} foldmethod=marker nospell:

general {
        col.active_border = rgba(78c6ebff) rgba(8289a380) 45deg
        col.inactive_border = rgba(7d838d80) rgba(4c566a50) 45deg
        col.nogroup_border_active = rgba(78c6ebff) rgba(8289a380) 45deg
        col.nogroup_border = rgba(7d838d80) rgba(4c566a50) 45deg
}

group {

        # Bborder color for active windows
        col.border_active = rgba(78c6ebff) rgba(8289a380) 45deg
        # Border color for inactive windows
        col.border_inactive = rgba(3C3C3Caa)

        groupbar {
                col.active = rgba(434c5ee6) rgba(4c566ae6) 45deg
                col.inactive = rgba(4c566a80)
                col.locked_active = rgba(bf616aff)
                col.locked_inactive = rgba(5e81acaa)
                text_color = rgba(77ABCBCC)
                text_color_inactive = rgba(d8dee980)
        }
}
