# vim: set sw=4 ts=4 sts=4 et tw=120 foldmarker={{{,}}} foldmethod=marker nospell:

general {
        col.active_border = rgba(a7c080ff) rgba(83c092ff) 45deg
        col.inactive_border = rgba(4f585e80) rgba(3d484d50) 45deg
        col.nogroup_border_active = rgba(a7c080ff) rgba(83c092ff) 45deg
        col.nogroup_border = rgba(4f585e80) rgba(3d484d50) 45deg
}

group {

        # Border color for active windows
        col.border_active = rgba(a7c080ff) rgba(83c092ff) 45deg
        # Border color for inactive windows
        col.border_inactive = rgba(3d484daa)

        groupbar {
                col.active = rgba(3d484de6) rgba(475258e6) 45deg
                col.inactive = rgba(343f4480)
                col.locked_active = rgba(e67e80ff)
                col.locked_inactive = rgba(7fbbb3aa)
                text_color = rgba(d3c6aacc)
                text_color_inactive = rgba(9da9a080)
        }
}
