general {
    col.active_border = rgba(dc8a78ff) rgba(8839efff) 45deg
    col.inactive_border = rgba(7287fdcc) rgba(179299cc) 45deg
}

group {
    col.border_active = rgba(dc8a78ff) rgba(8839efff) 45deg
    col.border_inactive = rgba(7287fdcc) rgba(179299cc) 45deg
    col.border_locked_active = rgba(dc8a78ff) rgba(8839efff) 45deg
    col.border_locked_inactive = rgba(7287fdcc) rgba(179299cc) 45deg
}
